### ISSUE TITLE
Dependency causing TypeError

### ISSUE THREAD

**Issue by Jessime** [wweir827/CHAMP#3]
Running `champ.parallel_louvain` crashes with:

```python
TypeError: find_partition() missing 1 required positional argument: 'partition_type'
```

This is because [louvain-igraph](https://github.com/vtraag/louvain-igraph/releases) has had some API changes. The fix should be easy though. I think you need to update [louvain_ext.py (line 1281)](https://github.com/wweir827/CHAMP/blob/master/champ/louvain_ext.py#L1281) to be:

```python
rp = louvain.find_partition(gr, louvain.RBConfigurationVertexPartition, weight=weight,  resolution_parameter=gamma)
```

**Comment by wweir827** [comment]
Thanks.  I realized that louvain has changed ( which is good because I should be able to add multilayer functionality now).
  
I just pushed a quick update to the github.  Let me know if the most recent version isn't working. 

I'll change the pypi version after i get the multilayer up and working .  

Cheers,
William

**Comment by Jessime** [comment]
It looks like we're up and running! 

I've cloned the repo, so I can submit pull requests in the future if I find additional changes.

**Comment by wweir827** [comment]
awesome thanks.

**Comment by Jessime** [comment]
And... just crashed out again:

```
Traceback (most recent call last):
  File "/home/jessime/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/jessime/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/jessime/Code/CHAMP/champ/louvain_ext.py", line 1319, in _run_louvain_parallel
    outparts=run_louvain(gfile,gamma,nruns=nruns,weight=weight,node_subset=node_subset,attribute=attribute,output_dictionary=True)
  File "/home/jessime/Code/CHAMP/champ/louvain_ext.py", line 1290, in run_louvain
    A=get_sum_internal_edges(rp,weight)
  File "/home/jessime/Code/CHAMP/champ/louvain_ext.py", line 1144, in get_sum_internal_edges
    sumA+= np.sum(subg.es[weight])
TypeError: unsupported operand type(s) for +=: 'int' and 'igraph.Edge'
```

**Comment by wweir827** [comment]
I'm having trouble duplicating this.  Are you using a weighted network? could you send me a test case and the command where you called parallel_louvain?

**Comment by Jessime** [comment]
Yea, I'm using weighted edges, which is what's causing the problem. I'll email you a path to my graph shortly. The command I used before was:

```python
partition_ensemble = champ.parallel_louvain(graph,
                                            start=.1,
                                            fin=5.1,
                                            numruns=10,
                                            weight=True,
                                            progress=True)
```

Based on the docstring:

> * weight – If True will use ‘weight’ attribute of edges in runnning Louvain and calculating modularity.

But `weight` gets handled a bit confusingly through the program.

---

I reran my input as:

```python
partition_ensemble = champ.parallel_louvain(graph,
                                            start=.1,
                                            fin=5.1,
                                            numruns=10,
                                            weight='weight',
                                            progress=True)
```

And surprisingly get a `RecursionError` (in part): 


```python
.
.
.
.
/home/jessime/Code/CHAMP/champ/louvain_ext.py in hdf5_file(self, value)
    232     def hdf5_file(self,value):
    233         '''Set new value for hdf5_file and automatically save to this file.'''
--> 234         self.hdf5_file=value
    235         self.save()
    236 

/home/jessime/Code/CHAMP/champ/louvain_ext.py in hdf5_file(self, value)
    232     def hdf5_file(self,value):
    233         '''Set new value for hdf5_file and automatically save to this file.'''
--> 234         self.hdf5_file=value
    235         self.save()
    236 

RecursionError: maximum recursion depth exceeded
```

I don't have any idea what's going on there.

**Comment by wweir827** [comment]
oh yeah i realized i never handled the case with weight=True instead of weight='weight'.  i've put a simple check to make sure.  If you put weight=True it expects the weights to be stored under 'weight'.  otherwise you can specify what key represents the edge weights in the graph.es .

**Comment by Jessime** [comment]
The `weight` keyword looks good. You have any thoughts on the recursion limit? 

Do I need to install anything for HDF5 outside of `h5py`?

**Comment by wweir827** [comment]
You know i hadn't seen that before.  I changed the internal name of the hdf5 file to avoid self reference.  Give it another go and see if it works.

**Comment by Jessime** [comment]
Still doing it, unfortunately. 

I'm not getting much information out of it, but for what it's worth, the top portion of the error is:

```python
RecursionError                            Traceback (most recent call last)
<ipython-input-19-fc976823616e> in <module>()
      4                                             numruns=10,
      5                                             weight='weight',
----> 6                                             progress=True)

/home/jessime/Code/CHAMP/champ/louvain_ext.py in parallel_louvain(graph, start, fin, numruns, maxpt, numprocesses, attribute, weight, node_subset, progress)
   1378     with terminating(Pool(processes=numprocesses)) as pool:
   1379         parts_list_of_list=pool.map(_run_louvain_parallel, parallel_args )
-> 1380 
   1381 
   1382     all_part_dicts=[pt for partrun in parts_list_of_list for pt in partrun]

/home/jessime/Code/CHAMP/champ/louvain_ext.py in __init__(self, graph, listofparts, name, maxpt, min_com_size)
    103     def __init__(self,graph=None,listofparts=None,name='unnamed_graph',maxpt=None,min_com_size=5):
    104 
--> 105         self._hdf5_file=None
    106         self.int_edges = np.array([])
    107         self.exp_edges = np.array([])

/home/jessime/Code/CHAMP/champ/louvain_ext.py in hdf5_file(self, value)
    232     def hdf5_file(self,value):
    233         '''Set new value for hdf5_file and automatically save to this file.'''
--> 234         self._hdf5_file=value
    235         self.save()
    236 
```

**Comment by wweir827** [comment]
did you restart you ipython kernel when you reloaded the module? Sometimes if you don't do that it doesn't recreate the objects correctly.

**Comment by Jessime** [comment]
Good call! I was assuming that having champ installed in dev. mode was good enough. 

I've submitted my first pull request for an attribute error I was getting while doing:

```python
partition_ensemble.get_CHAMP_partitions()
```

I've only done a few pull requests before, so let me know if I didn't do it properly.
